# Copyright 2021 The Telemetry Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

project_name: telemetry-client
before:
  hooks:
    - make test
    - make lint
release:
  github:
    owner: kubermatic
    name: telemetry-client
  prerelease: true
builds:
  - &build-reporter
    id: reporter
    binary: reporter
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/reporter/main.go
  - <<: *build-reporter
    id: kubernetes-agent
    binary: kubernetes-agent
    main: cmd/kubernetes-agent/main.go
  - <<: *build-reporter
    id: kubermatic-agent
    binary: kubermatic-agent
    main: cmd/kubermatic-agent/main.go
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256
dockers:
  - &docker
    goos: linux
    goarch: amd64
    binaries:
      - reporter
    builds:
      - reporter
    image_templates:
      - "quay.io/kubermatic/telemetry-reporter:latest"
      - "quay.io/kubermatic/telemetry-reporter:{{ .Tag }}"
      - "quay.io/kubermatic/telemetry-reporter:v{{ .Major }}"
    dockerfile: config/dockerfiles/reporter.Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - <<: *docker
    binaries:
      - kubernetes-agent
    builds:
      - kubernetes-agent
    image_templates:
      - "quay.io/kubermatic/telemetry-kubernetes-agent:latest"
      - "quay.io/kubermatic/telemetry-kubernetes-agent:{{ .Tag }}"
      - "quay.io/kubermatic/telemetry-kubernetes-agent:v{{ .Major }}"
    dockerfile: config/dockerfiles/kubernetes-agent.Dockerfile
  - <<: *docker
    binaries:
      - kubermatic-agent
    builds:
      - kubermatic-agent
    image_templates:
      - "quay.io/kubermatic/telemetry-kubermatic-agent:latest"
      - "quay.io/kubermatic/telemetry-kubermatic-agent:{{ .Tag }}"
      - "quay.io/kubermatic/telemetry-kubermatic-agent:v{{ .Major }}"
    dockerfile: config/dockerfiles/kubermatic-agent.Dockerfile
